id: PA4203333
initial_creation_type: input
source_metadata:
  title: Khenpo Pema Vajra Series
  language: bo
  description: Texts by and about the Dzogchen scholar Khenpo Pema Vajra (padma badzra,
    c. 1807–1884), also known as Khenpo Pema Dorje.
  volume:
    d2c01c0ca7fa48fd88d0bf4e78aba9c3:
      title: A Liberating Reminder
      parent: Advice
    d68846bb75b24ec6a0d5371a01db70c8:
      title: The Life of Khenpo Pema Vajra
      parent: Biography
    d782e60a6dfa47a2a99c0c5e467041b4:
      title: A Brief Overview of the Three Turnings and the Mantra Piṭaka of the Vidyādharas
      parent: Commentaries
    e9fad47648e34a01a6909916e3088177:
      title: 'Words from the Lineage Masters to Clarify Maitreyanātha''s Vision: An
        Overview of the Perfection of Wisdom''s Ornament of Realization'
      parent: Commentaries
    9f79c2ca58fc4153a545370e9d7f15cb:
      title: A Clear and Concise Description of the Practice of Śamatha
      parent: Meditation
    6867994acab14e7cafb89b84802603a5:
      title: Brief Light Offering Prayer
      parent: Prayers
created_at: '2022-03-01T00:26:49.561971'
last_modified_at: '2022-03-01T00:26:49.561974'
statistics:
  total_words: 16907
  total_non_words: 1665
quality:
  non_words_ratio: 0.1
